version: '3.7'
services:
  ejbca:
    environment:
      - httpsserver_hostname=localhost
      - database_host=ejbca
      - database_name=ejbcatest
      - database_username=ejbca
      - database_password=ejbca
      - database_type=h2
      - database_port=
      - superadmin_cn=SuperAdmin2020
      - ca_name=Management
      - BASE_DN=O=My Example CA 2020,C=DE
      - SOURCE=mounted
    build:
      context: .
    ports:
      - "8443:8443"
      - "8080:8080"
      - "9990:9990"
      - "9993:9993"
    volumes:
      - ./ejbca_src:/ejbca
      - ./workspace:/home/ejbca
      - ./ejbca-setup:/root/ejbca-setup
    hostname: ejbca-dev
    logging:
      driver: json-file
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "/bin/nc -z 127.0.0.1 8080 > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

